In [ ]:
# Author: Clinton Daniel, University of South Florida
# Date: 4/4/2023
# Description: This python script assumes that you already have
# a database.db file at the root of your workspace.
# This python script will CREATE a table called students 
# in the database.db using SQLite3 which will be used
# to store the data collected by the forms in this app
# Execute this python script before testing or editing this app code. 
# Open a python terminal and execute this script:
# python create_table.py

import sqlite3
import pandas as pd
conn = sqlite3.connect('database.db')
print("Connected to database successfully")

cursor = conn.cursor()

# user
# Example data with four values for each row
# users_data = [
#     ('john_doe', 'John Doe', 'john@example.com', 'password123'),
#     ('jane_smith', 'Jane Smith', 'jane@example.com', 'password456'),
#     ('alice_jones', 'Alice Jones', 'alice@example.com', 'password789')
# ]

# Insert data into the 'user' table
# cursor.executemany("INSERT INTO user (username, fullname, email, password) VALUES (?, ?, ?, ?)", users_data)


# cursor.execute(f'DROP TABLE IF EXISTS book')
conn.execute('ALTER TABLE user_book ADD COLUMN finish_date DATE')
# conn.execute('CREATE TABLE IF NOT EXISTS user_book (username TEXT PRIMARY KEY,book_id INTEGER NOT NULL,status TEXT,note TEXT)')

# conn.execute('CREATE TABLE IF NOT EXISTS book_rating (book_id INTEGER PRIMARY KEY,rating_count INTEGER NOT NULL,review_count INTEGER NOT NULL,avr_count REAL NOT NULL)')
# conn.execute('CREATE TABLE IF NOT EXISTS book_info (book_id INTEGER PRIMARY KEY,page_numbers INTEGER NOT NULL,awards TEXT ,description DATE)')
# conn.execute('CREATE TABLE IF NOT EXISTS genre (genre_id INTEGER PRIMARY KEY,name INTEGER NOT NULL)')
# conn.execute('CREATE TABLE IF NOT EXISTS author (author_id INTEGER PRIMARY KEY,name TEXT NOT NULL, gender TEXT NOT NULL,biography TEXT NOT NULL,country TEXT NOT NULL)')
# conn.execute('CREATE TABLE IF NOT EXISTS author_rating (author_id INTEGER PRIMARY KEY,fan_count INTEGER NOT NULL,avr_rating REAL,review_count INTEGER)')

# excel_file_path = '/Users/trantienlong/Documents/Zalo Received Files/books.xlsx'
# df = pd.read_excel(excel_file_path)

# Define the table name
# table_name = 'book'

# df.to_sql(table_name, conn, index=False, if_exists='replace',
#           dtype={'book_id': 'INTEGER', 'title': 'TEXT', 'genre_id': 'TEXT','author_id': 'TEXT',
#                  'date_published': 'TEXT'})
# id	title	date_published	authorid	number_of_pages	description	awards
# Commit the changes

conn.commit()

print("Created table successfully!")

conn.close()